version: '3.9'

volumes:
  mysql_data: {}

  apache_logs: 
    driver: local 
    driver_opts:
      type: none
      o: bind
      device: /var/log/apache2

services:
  mysql:
    image: mysql:latest
    volumes:
      - /home/ubuntu/mysql_data:/var/lib/mysql
    ports:
     - "3306:3306"  
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projeto
      MYSQL_USER: projeto
      MYSQL_PASSWORD: projeto

  web:
    image: gabrielfkoerich/techchallenge:1.1
    ports:
      - "80:80"
    restart: always
    depends_on:
      - mysql
    volumes:
      - apache_logs:/var/log/apache2 

    environment:
      - DB_HOST=mysql
      - DB_DATABASE=projeto
      - DB_USERNAME=projeto
      - DB_PASSWORD=projeto