FROM php:8.2-apache

RUN apt-get update && \
    apt-get install -y vim &&\
    apt-get install -y git unzip && \
    docker-php-ext-install pdo pdo_mysql && \
    curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer


WORKDIR /var/www

RUN git clone https://github.com/Gabrielkoeric/TechChallenge.git

RUN cp /var/www/TechChallenge/projeto/.env.example /var/www/TechChallenge/projeto/.env

RUN sed -i 's|DocumentRoot /var/www/html|DocumentRoot /var/www/TechChallenge/projeto/public|' /etc/apache2/sites-available/000-default.conf
RUN sed -i 's|<Directory /var/www/html>|<Directory /var/www/TechChallenge/projeto/public>|' /etc/apache2/apache2.conf

WORKDIR /var/www/TechChallenge/projeto

RUN composer install --no-dev --optimize-autoloader

RUN php artisan key:generate --force

RUN composer require "darkaonline/l5-swagger" && \
    php artisan vendor:publish --provider="L5Swagger\L5SwaggerServiceProvider"

RUN chown -R www-data:www-data /var/www/TechChallenge/projeto/storage /var/www/TechChallenge/projeto/bootstrap/cache

RUN a2enmod rewrite

EXPOSE 80

CMD ["apache2-foreground"]
